const GET_TEAMS = 'GET_TEAMS'
const GET_TEAM_INFO = 'GET_TEAM_INFO'
const GET_TEAM_ROSTER = 'GET_TEAM_ROSTER'
const GET_PLAYER_INFO = 'GET_PLAYER_INFO'
const GET_PLAYER_STATS = 'GET_PLAYER_STATS'

export default {
  GET_TEAMS,
  GET_TEAM_INFO,
  GET_TEAM_ROSTER,
  GET_PLAYER_INFO,
  GET_PLAYER_STATS
}
